- project:
    check:
      jobs:
        - vitrage-dsvm-api-py27
        - vitrage-dsvm-datasources-py27
        - vitrage-dsvm-api-py35:
            branches: ^(?!stable/(newton|ocata|pike)).*$
        - vitrage-dsvm-datasources-py35:
            branches: ^(?!stable/(newton|ocata|pike)).*$
    gate:
      jobs:
        - vitrage-dsvm-api-py27
        - vitrage-dsvm-datasources-py27
        - vitrage-dsvm-api-py35
        - vitrage-dsvm-datasources-py35

- job:
    name: vitrage-dsvm-api-py27
    parent: legacy-dsvm-base
    run: playbooks/legacy/vitrage-dsvm-api-py27/run.yaml
    post-run: playbooks/legacy/vitrage-dsvm-api-py27/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/mistral
      - openstack/python-vitrageclient
      - openstack/vitrage
      - openstack/vitrage-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: vitrage-dsvm-api-py35
    parent: legacy-dsvm-base
    run: playbooks/legacy/vitrage-dsvm-api-py35/run.yaml
    post-run: playbooks/legacy/vitrage-dsvm-api-py35/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/mistral
      - openstack/python-vitrageclient
      - openstack/vitrage
      - openstack/vitrage-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: vitrage-dsvm-datasources-py27
    parent: legacy-dsvm-base
    run: playbooks/legacy/vitrage-dsvm-datasources-py27/run.yaml
    post-run: playbooks/legacy/vitrage-dsvm-datasources-py27/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/mistral
      - openstack/python-vitrageclient
      - openstack/vitrage
      - openstack/vitrage-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: vitrage-dsvm-datasources-py35
    parent: legacy-dsvm-base
    run: playbooks/legacy/vitrage-dsvm-datasources-py35/run.yaml
    post-run: playbooks/legacy/vitrage-dsvm-datasources-py35/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/mistral
      - openstack/python-vitrageclient
      - openstack/vitrage
      - openstack/vitrage-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
